### ISSUE TITLE
s.monitor('top.CLOCK') error

### ISSUE THREAD

**Issue by chaekwan** [tianzhuqiao/bsmedit#1]
Hello Tianzhu,
Thanks for your great work on making SystemC simulation easy.

While following the instructions, I got the following error during simulation.

s.monitor('top.CLOCK')
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/apps/hosted/tools/python/anaconda3-2019.10/lib/python3.7/site-packages/bsmedit/bsm/sim.py", line 258, in monitor
    obj = self.objects.get(name, None)
AttributeError: 'NoneType' object has no attribute 'get'

My platform is as follows:
- OS: Ubuntu 18.04
- gcc : gcc-7.4.0
- python : anaconda3-2019.10

Can I get your help?

Thanks,
Chaekwan

**Comment by tianzhuqiao** [comment]
Thanks for the report, Chaekwan.  It looks like the simulation is not created successfully. How do you create your simulation? Is your path to your simulation valid?  You can call "is_valid" to confirm.

```
>>> s = simulation(None, './examples/libstart.so')
>>> s.is_valid()
True
```

And v3.2.1 has some other bugs. Can you try the master branch?  
The doc/example is also a little bit old. The "current" way to set the "spin" control style is:
```
s.monitor('top.CLOCK')
p = s.monitor('top.sig_steps')
p.SetFormatter(fmt.IntFormatter(256, 2**16)) # min=256, max=2**16 
p.SetControlStyle('spin')
```
